spring:
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: password
           
    

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:8080/realms/book-realm 
    main:
    allow-circular-references: true      
