eureka:
  client:
    service-url:
      default-zone: http://eureka-server
spring:
   cloud:
    gateway:
      routes:
      - id: fullstackserver
        uri: lb://FULLSTACK-SERVICE
        predicates:
        - Path=book-crudApi/** 
      - id: fullstackserver
        uri: lb://FULLSTACK-RETRIEVE
        predicates:
        - Path=book-getApi/**   



