eureka:
  client:
    service-url:
      default-zone: http://eureka-server
spring:
   main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
   cloud:
    gateway:
    
      default-filters:

        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:

        corsConfigurations:

          '[/**]':

              allowedOrigins: "*"

              allowedMethods: "*"

              allowedHeaders: "*"
      routes:
      - id: fullstackserver
        uri: lb://FULLSTACK-SERVICE
        predicates:
        - Path=book-crudApi/** 
      - id: fullstackserver
        uri: lb://FULLSTACK-RETRIEVE
        predicates:
        - Path=book-getApi/**   



